import type { Metadata } from "next";
import {
  Google_Sans_Code,
  Inter,
  Poppins,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Footer from "@/components/layout-comp/footer";

const primaryFont = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const secondaryFont = Poppins({
  variable: "--font-secondary",
  weight: ["300", "400", "700", "500", "600"],
  subsets: ["latin"],
});

const codeFont = Google_Sans_Code({
  variable: "--font-code",
  weight: ["300", "400", "700", "500", "600", "800"],
  subsets: ["latin"],
  fallback: [
    "ui-monospace",
    "SFMono-Regular",
    "Consolas",
    "Liberation Mono",
    "Menlo",
    "monospace",
  ],
});

export const metadata: Metadata = {
  title: "Create Nextsd App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} ${codeFont.variable} antialiased font-regular min-h-screen `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-full">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
